### ISSUE TITLE
Configuration of path to java runtime for VSCode

### ISSUE THREAD

**Issue by jvallade** [ThalesGroup/xsmp-modeler-core#40]
Hi,

I just tried installing the VSCode extension, using the provided vsix file. The extension crashes at start-up because it detects an old version of Java. I'm using my company laptop to test this, and the system install of Java is indeed an old one (1.8). I have several JDK available, but I'm not sure how to tell the extension to use these ones instead (I tried setting a JAVA_HOME env variable but it does not solve the issue). 

Thanks for your help.

**Comment by jvallade** [comment]
I'm on Windows. 
I had a quick look at the link you provided. There is an issue : as I'm not administrator on my laptop, I can't edit the system level PATH env variable (I tried before writing the issue to edit user PATH env variable, but I think the system one has precedence, hence the system install of Java is used...). 

I'll try to remove the system install of Java and see if it gets properly removed from the Path (to be honest I'm not confident it will).

In any case, I think it could be a good improvement to have some meaningful configuration parameters available to the extension 😉 . What do you think ?

**Comment by ydaveluy** [comment]
I'm not very familiar with VS code extensions and good code practices.

In the extension Java seems to be called from [here](https://github.com/ThalesGroup/xsmp-modeler-core/blob/7a88366a63176eefb1fcb5d648d9f187ba705faa/org.eclipse.xsmp.vscode_extension/src/extension.ts#L26)

I suppose that it would be possible to use a specific environment variable instead of 'java'.

**Comment by jvallade** [comment]
I tried removing this old Java version but of course I need admin privileges (and need to make a ticket and maybe I'll get rid of this install). 

In the meantime, I had a look at [this](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration) and it seems to be quite easy to add a new configuration parameter. If I was sure to be able to build the extension on my laptop I'd love to propose a pull request, but I'm afraid it will take me forever to set up the development environment to test the evolution before creating a proper pull request. 

Let me know if you think you'll find some time any time soon to do something about this 😄 . Otherwise, I'll see if I can make something about it.

**Comment by ydaveluy** [comment]
I think this VS Code extension is not compatible with Windows even with a good java version.
On an other extension using java I found there is a conditional to select java or java.exe depending on the platform:
https://github.com/opencaesar/oml-luxor/blob/53de904dd883bc847dd00b2b7090ae03af2c9942/extension/src/oml-lsp-extension.ts#L170

I will try to add a configuration parameter but I don't have a Windows environment to test it.

**Comment by ydaveluy** [comment]
I just pushed a fix with a temporary tag [v1.1.0-rc3_tmp](https://github.com/ThalesGroup/xsmp-modeler-core/releases/tag/v1.1.0-rc3_tmp). The build process will automatically generate the artifacts.
In the extension configuration you should be able to specify the path of your java executable.
I don't have a proper environment to test this fix, let me know if it solves your problem.
I will generate an rc4 if the fix is ok

**Comment by jvallade** [comment]
Thanks for the quick patch. Unfortunately, it seems that the configuration item is not taken into account. It tried setting the following : 
```json
{
    "javaPath": "c:\\path\\to\\java.exe",
}
```
in both my user settings and in the workspace settings. I always have the same error. I tried setting a path with forward slash, as well as a dummy value and still it seems to be using the default value. Am I missing something ?

I had a look at the code and could not spot an obvious issue... The configuration definition in the `package.json` seems to be a little different from the one in example [here](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration) but the parameter is visible on the extension page in VSCode and the auto-completion is working just fine on the `settings.json` so VSCode seems to be happy with your definition.

I'm not sure of the way forward here. If it can help I can make myself available for a call to see if we can debug somehow together (but this will have to wait next week though).

**Comment by ydaveluy** [comment]
Ok I think It's fixed now.

```
{
    "xsmp.javaPath": "c:\\path\\to\\java.exe",
}
```

I regenerated the tmp release

**Comment by jvallade** [comment]
Hi,
I tried downloading the tmp release again, but it seems like this is still the first version of the patch: the expected configuration parameter is still `javaPath`. Looking at the code / code actions, I think you pushed on the main branch, but the tag is still on the former commit.

**Comment by ydaveluy** [comment]
You're right, sorry. It was a bit late yesterday evening :-)
The build with correct tag is in progress

**Comment by jvallade** [comment]
It seems that the [action](https://github.com/ThalesGroup/xsmp-modeler-core/actions/runs/6105947586) failed 😅

**Comment by ydaveluy** [comment]
This time it should be ok: https://github.com/ThalesGroup/xsmp-modeler-core/releases/tag/v1.1.0-rc3_tmp

By default the extension will run java.exe on Windows otherwise java.
If the setting xsmp.javaPath is set, it will be used. In case the setting is changed, the server is restarted with the new java.
In case the provided java path is invalid the extension stopped and you will have to reload vscode to take into account a new setting.

I have now a configured environment to build the vscode extension and test it.

**Comment by jvallade** [comment]
Thanks ! I'm now able to load the extension in VSCode. I'm going to close this thread, but I might open a few more to improve usability 😄.
Thanks for your help.
